# Generated by Django 3.1.3 on 2020-11-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201125_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.TextField(blank=True, default='defaultSum'),
            preserve_default=False,
        ),
    ]
